### ISSUE TITLE
Osler adpater not consuming full reposne from QGateway

### ISSUE THREAD

**Issue by fieranmason** [PhysiciansDataCollaborative/knowledge-base#92] opened 2015-10-13 22:21 UTC

**Comment by fieranmason** [comment] 2015-10-13 22:23
The problem is that there are two 'ok' aka 200 reponse situations --- 1 - the record is received and imported without error 2 - the record is recieved and successfully filtered out based on the absence of the assignedAuthor id in the provider.txt file.

**Comment by DerekRoberts** [comment] 2015-10-23 03:14
Duplicate of #91.

**Comment by fieranmason** [comment] 2015-10-23 05:57
Not a duplicate --- different details for Oscar and Osler

**Comment by DerekRoberts** [comment] 2021-02-11 19:48
Archived.

**Closed as completed by DerekRoberts** 2021-02-11 19:48 UTC
